version: '3.9'
services:
  api:
    build:
      context: ../
      dockerfile: build/api.Dockerfile
    image: forum-api
    ports:
      - 127.0.0.1:5000:8000
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: forum
      DB_USER: forum
      DB_PASSWORD: password
    restart: on-failure
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  db:
    build:
      context: ../
      dockerfile: build/postgres.Dockerfile
    image: forum-db
    environment:
      BACKUP: /init.sql
      POSTGRES_DB: forum
      POSTGRES_USER: forum
      POSTGRES_PASSWORD: password
